### PR TITLE
:recycle: migrate departures endpoint to use TRWL-ID

### LINKED ISSUE #2390: Check-in from Bergün/Bravougn not possible
### Describe the bug

The connection search from Bergün/Bravuogn seems to work at first and redirects to https://traewelling.de/trains/stationboard?station=Berg%C3%BCn/Bravuogn

However, the departures of the trains from Bergün/Bravuogn station are not displayed there, but those from "Bergün/Bravuogn SBAD", the valley station of the distant Darlux chairlift: https://traewelling.de/trains/stationboard?station=Berg%C3%BCn/Bravuogn%20SBAD

Location-based search works to some extent: However, it never worked for me on the Pixel 7 Pro and Pixel 8 Pro either, sometimes on an iPhone under Safari and on a Pixel 7 under Chrome. On the Pixel 7 Pro and 8 Pro, I am then redirected to the post bus station at the train station, "Bergün/Bravuogn, staziun", where the chairlift appears in addition to the rarely running buses, instead of only the expected bus connections, and possibly, if linked to the train station, those of the trains.

Anklicken eines vorhandenen, per Mitfahren unter Träwelldroid getätigten" Check-ins ab Bergün/Bravuogn leitet auf https://traewelling.de/trains/stationboard?provider=train&station=8509197 um. Diese Nummer scheint soweit korrekt zu sein, aber auch so werden nur die Abfahrten ab "Bergün/Bravuogn SBAD" angezeigt.

### Steps to reproduce

1. Go to https://traewelling.de/dashboard
2. Search for Bergün/Bravougn
3. Choose Bergün/Bravougn as your starting point
4. Attempts to check-in to the trains departing there but not displayed

### Browser console logs

_No response_

### Browser

_No response_

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
(when Vue is adapted, this PR fixes #2390)

This PR changes the API Endpoint for getting departures from the stations query string to the Träwelling ID.

### CODE REVIEW

**Comment by MrKrisKrisu** [comment]
@HerrLevin Can you adapt the Vue Implementation for the new check-in flow to the Träwelling ID? I put a `ToDo`-Note there for you. Feel free to push in this branch.

File: tests/Feature/APIv1/TransportTest.php [hunk 1]
```diff
@@ -22,11 +23,11 @@ public function testGetDeparturesFetchTripAndCheckin(): void {
                    ]);
 
         //Test departures
-        $station   = self::FRANKFURT_HBF['name'];
+        $station   = Station::factory(['ibnr' => self::FRANKFURT_HBF['id'], 'name' => self::FRANKFURT_HBF['name']])->create();
         $timestamp = Date::parse('next monday 8 am');
         $this->actAsApiUserWithAllScopes();
-        $response  = $this->get(
-            uri:     '/api/v1/trains/station/' . $station . '/departures?when=' . urlencode($timestamp->toIso8601String()),
+        $response = $this->get(
```
Comment (HerrLevin) [inline tests/Feature/APIv1/TransportTest.php:164]: Since the old endpoint is still in use, I'd prefer you to duplicate the test class, so that we can still run tests on the old endpoint + test the new one.

File: app/Http/Controllers/API/v1/TransportController.php [hunk 2]
```diff
@@ -130,56 +163,58 @@ class TransportController extends Controller
...
         $validated = $request->validate([
                                             'when'       => ['nullable', 'date'],
                                             'travelType' => ['nullable', new Enum(TravelType::class)],
                                         ]);
 
+        $timestamp = isset($validated['when']) ? Carbon::parse($validated['when']) : now();
+        $station   = Station::findOrFail($stationId);
+
         try {
-            $trainStationboardResponse = TransportBackend::getDepartures(
```
Comment (HerrLevin) [inline app/Http/Controllers/API/v1/TransportController.php:166]: Maybe also mark `TransportBackend::getDepartures` as deprecated + remove its usage in the admin panel + add removal TODO?

File: app/Http/Controllers/API/v1/TransportController.php [hunk 3]
```diff
@@ -130,56 +163,58 @@ class TransportController extends Controller
...
+                                    ],
+                                ]
+                            ]
             );
         } catch (HafasException) {
             return $this->sendError(__('messages.exception.generalHafas', [], 'en'), 502);
         } catch (ModelNotFoundException) {
             return $this->sendError(__('controller.transport.no-station-found', [], 'en'));
+        } catch (Exception $exception) {
+            report($exception);
```
Comment (HerrLevin) [inline app/Http/Controllers/API/v1/TransportController.php:215]: 👍

**Review by HerrLevin — CHANGES_REQUESTED** [review]

File: app/Http/Controllers/API/v1/TransportController.php (hunk 2 above)
Comment (MrKrisKrisu) [reply app/Http/Controllers/API/v1/TransportController.php:166]: I'll mark it as deprecated but prefer to remove the usage elsewhere in other PRs.

**Review by HerrLevin — APPROVED** [review]
