### PR TITLE
🗃️ Add unique key to TrainCheckin

### LINKED ISSUE #231: Prevent checking in twice to the same trip
**Describe the bug**
If you press the check-in button quickly enough, you may create the same check-in twice and bypass the check to see if you are already checked in.

We should create a Unique DB-Key for the TrainCheckIn. Maybe something like UserID-TripID-Departure so users can check in multiple times in the same trip. This is important for example ring lines. The problem is, that the train_checkins table doesn't know the UserID. 

**Additional context**
See https://twitter.com/f2k1de/status/1364239482032185351
See https://twitter.com/detraxLIVE/status/1364274967395897349
See https://twitter.com/andizgl/status/1398690711168552960
See https://twitter.com/T1matix_/status/1398691727976943621

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
Good luck to the person who has to clean the database from duplicates beforehand.
Oh, that's me? Shit! 💩

fixes #231

### CODE REVIEW

**Comment by MrKrisKrisu** [comment]
@HerrLevin  Please review this, but **DO NOT MERGE** it. I want to clean the database first before the release.

File: database/migrations/2021_11_03_211948_add_unique_key_to_train_checkins.php [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+use Illuminate\Database\Migrations\Migration;
+use Illuminate\Database\Schema\Blueprint;
+use Illuminate\Support\Facades\Schema;
+
+class AddUniqueKeyToTrainCheckins extends Migration
+{
+
+    public function up(): void {
+        Schema::table('train_checkins', function(Blueprint $table) {
+            $table->unique(['user_id', 'trip_id', 'origin', 'departure'], 'user_trip_origin_departure');
```
Comment (HerrLevin) [inline database/migrations/2021_11_03_211948_add_unique_key_to_train_checkins.php:12]: Oooooof. 😂

**Review by HerrLevin — APPROVED** [review]

**Comment by MrKrisKrisu** [comment]
cleaned up 752 duplicate checkins.
