### PR TITLE
Fixed a bug wherein the flags "true" or "false" would not change the …

### LINKED ISSUE #88: API: /trains/checkin will always post a tweet
**Describe the bug**
Given that your Traewelling account is linked with your Twitter account, checking into a train using `/trains/checkin` with valid tripID, start and stop station (with workaround described in #72) will always post a tweet no matter what the "tweet" option is set to. 

**To Reproduce**
Have your Traewelling account linked with your Twitter account. Then:
```
curl -v https://traewelling.de/api/v0/trains/checkin -H 'authorization: Bearer ...' -H 'content-type: application/json' -d '{"tripID":"...","start":"...","destination":"...","tweet":false,"toot":false,"body":null}'
```
This will always result in a tweet on Twitter, even if "tweet" is false.

**Expected behavior**
No tweets should be posted if "tweet" is false.

### PR DESCRIPTION
**Pull request by HerrLevin**
…behavior of tweeting/tooting. Also a (potential) bug wherein a user could not check in to a "exit only"-train.

fixes #88.

### CODE REVIEW

**Review by MrKrisKrisu — APPROVED** [review]

File: app/Http/Controllers/TransportController.php [hunk 1]
```diff
@@ -378,7 +381,7 @@ public static function TrainCheckin($tripId,
                 $postText .= $appendix;
             }
 
-            if (isset($tootCheck) && $user->socialProfile) {
+            if (isset($tootCheck) && $tootCheck != false && $user->socialProfile) {
```
Comment (MrKrisKrisu) [inline app/Http/Controllers/TransportController.php]: Maybe use !== to check if $tootCheck is 0 e.g.?

File: app/Http/Controllers/TransportController.php [hunk 2]
```diff
@@ -390,7 +393,7 @@ public static function TrainCheckin($tripId,
                     Log::error($e);
                 }
             }
-            if (isset($tweetCheck) && $user->socialProfile) {
+            if (isset($tweetCheck) && $tweetCheck != false && $user->socialProfile) {
```
Comment (MrKrisKrisu) [inline app/Http/Controllers/TransportController.php]: Maybe use !== to check if $tootCheck is 0 e.g.?

**Review by MrKrisKrisu — CHANGES_REQUESTED** [review]

**Review by MrKrisKrisu — APPROVED** [review]

**Review by jeyemwey — APPROVED** [review]
