### PR TITLE
🗃️ Replace kilometers with meters

### LINKED ISSUE #448: Save distance in train_checkins in meters
Save distance in train_checkins in meters

### LINKED ISSUE #523: [APIv1] 1 point for any check-in
**Describe the bug**
When using APIv1 for any check-in, you'll however only gain one point for that journey.

**To Reproduce**

1. Create a check-in via API v1
2. See response, one point is given to the user

**Expected behavior**
The correct amount of points (using the calculation formula) is given to the user.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
closes #448

fixes #523

### CODE REVIEW

File: database/migrations/2021_08_05_211128_change_column_for_train_checkins.php [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+use Illuminate\Support\Facades\DB;
+use Illuminate\Support\Facades\Schema;
+
+class ChangeColumnForTrainCheckins extends Migration
+{
+
+    public function up(): void {
+        Schema::table('train_checkins', function(Blueprint $table) {
+            $table->unsignedInteger('distance')
+                  ->comment('meter')
```
Comment (HerrLevin) [inline database/migrations/2021_08_05_211128_change_column_for_train_checkins.php]: meter**s**

File: app/Http/Controllers/Backend/GeoController.php [hunk 2]
```diff
@@ -120,6 +119,6 @@ public static function calculateDistanceBetweenCoordinates(
         $distance = acos(sin($latA) * sin($latB) + cos($latA) * cos($latB) * cos($lonB - $lonA))
                     * $equatorialRadiusInKilometers;
 
-        return round($distance, $decimals);
+        return round($distance, 3) * 1000;
```
Comment (HerrLevin) [inline app/Http/Controllers/Backend/GeoController.php]: Change `$equatorialRadiusInKilometers = 6378.137;` to  `$equatorialRadiusInMeters = 6378137;` and return `round($distance, 0)`

File: app/Http/Controllers/StatusController.php [hunk 3]
```diff
@@ -302,7 +302,7 @@ public static function ExportStatuses(
                                                   $t->trainCheckin->Destination->latitude . ', ' . $t->trainCheckin->Destination->longitude,
                                                   $t->trainCheckin->arrival,
                                                   $interval->h . ":" . sprintf('%02d', $interval->i),
-                                                  $t->trainCheckin->distance,
+                                                  $t->trainCheckin->distance / 1000,
```
Comment (HerrLevin) [inline app/Http/Controllers/StatusController.php]: this is fine, since our export has always been in km but maybe round this?

File: app/Http/Controllers/TransportController.php [hunk 4]
```diff
@@ -299,7 +299,7 @@ public static function TrainCheckin($tripId,
         }
 
         $points = self::CalculateTrainPoints(
```
Comment (HerrLevin) [inline app/Http/Controllers/TransportController.php]: Please refactor this method to accept meters.

File: app/Http/Controllers/TransportController.php [hunk 5]
```diff
@@ -385,7 +385,7 @@ public static function TrainCheckin($tripId,
             'points'               => $trainCheckin->points,
             'alsoOnThisConnection' => $trainCheckin->alsoOnThisConnection,
             'lineName'             => $hafasTrip->linename,
-            'distance'             => $trainCheckin->distance,
+            'distance'             => $trainCheckin->distance / 1000,
```
Comment (HerrLevin) [inline app/Http/Controllers/TransportController.php]: this should return meters and the frontend should catch it.

File: app/Models/TrainCheckin.php [hunk 6]
```diff
@@ -128,7 +127,7 @@ public function getDurationAttribute(): int {
     }
 
     public function getSpeedAttribute(): float {
-        return $this->duration == 0 ? 0 : $this->distance / ($this->duration / 60);
+        return $this->duration == 0 ? 0 : ($this->distance / 1000) / ($this->duration / 60);
```
Comment (HerrLevin) [inline app/Models/TrainCheckin.php:134]: 🤓
```suggestion
        return $this->duration == 0 ? 0 : ($this->distance) / ($this->duration * 60) * 3.6;
```
(have not tested it though)

**Review by HerrLevin — CHANGES_REQUESTED** [review]

File: app/Http/Controllers/TransportController.php (hunk 5 above)
Comment (MrKrisKrisu) [reply app/Http/Controllers/TransportController.php]: That is currently too much effort for me. I don't want to search in a thousand places. (APIv0, APIv1, Frontend)

Anyway this method should just return the TrainCheckIn instead of an array.

**Review by HerrLevin — APPROVED** [review]
