### PR TITLE
:bug: Fix unauthenticated profile view

### LINKED ISSUE #725: HTTP 500 on profile pages
**Describe the bug**
Non-logged-in users receive an HTTP 500 error when calling any profile

**Additional context**
The cause is probably the new policy, which throws a NullPointerException. (Only a suspicion, not tested).

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
fixes #725

### CODE REVIEW

File: app/Http/Controllers/UserController.php [hunk 1]
```diff
@@ -39,17 +40,15 @@ public static function updateProfilePicture($avatar): array {
...
-    public static function getProfilePage($username): ?array {
+    public static function getProfilePage(string $username, Controller $controller): ?array {
         $user = User::where('username', 'like', $username)->first();
         if ($user === null) {
             return null;
         }
         try {
-            $statuses = UserController::statusesForUser($user);
-        } catch (PermissionException) {
+            $controller->authorize('view', $user);
```
Comment (HerrLevin) [inline app/Http/Controllers/UserController.php]: Gate::authorize

File: app/Http/Controllers/API/StatusController.php [hunk 2]
```diff
@@ -63,7 +63,7 @@ public function index(Request $request) {
             $statuses['statuses'] = DashboardController::getPrivateDashboard(Auth::user());
         }
         if ($view === 'user') {
-            $statuses = UserBackend::getProfilePage($request->username);
+            $statuses = UserBackend::getProfilePage($request->username, $this);
```
Comment (HerrLevin) [inline app/Http/Controllers/API/StatusController.php]:
```suggestion
            $statuses = UserBackend::getProfilePage($request->username);
```

**Review by HerrLevin — APPROVED** [review]
