### PR TITLE
🩹 Fixed TwitterNotSentNotification

### LINKED ISSUE #237: Notifications broken on desktop and mobile
**Describe the bug**
Notifications are not displayed on desktop and mobile - when analysing the request, a HTTP error with status 500 occures.

**To Reproduce**
1. Open notifications panel on any device

**Expected behavior**
Notifications are loaded and displayed

**Screenshots**
image
image
image

**Additional context**
I recently changed my password on Twitter, but I think, this should nothing have to do with that

### PR DESCRIPTION
**Pull request by MrKrisKrisu**
fixes #237

### CODE REVIEW

File: app/Notifications/TwitterNotSent.php [hunk 1]
```diff
@@ -5,73 +5,73 @@
...
-
         return view("includes.notification", [
-            'color' => "warning",
-            'icon' => "fas fa-exclamation-triangle",
-            'lead' => __('notifications.socialNotShared.lead', ['platform' => "Twitter"]),
-            "link" => route('statuses.get', ['id' => $detail->status->id]),
+            'color'  => "warning",
+            'icon'   => "fas fa-exclamation-triangle",
+            'lead'   => __('notifications.socialNotShared.lead', ['platform' => "Twitter"]),
+            "link"   => route('statuses.get', ['id' => $data['status_id']]),
```
Comment (MrKrisKrisu) [inline app/Notifications/TwitterNotSent.php:69]: This line is the whole change. We have tried to access a variable that does not exist.

**Review by HerrLevin — APPROVED** [review]
