### PR TITLE
🩹 Fix second to last cancelled stop

### LINKED ISSUE #21: [ASSUMPTION] "Last station cancelled" may result in "second to last station cancelled"
**Describe the bug**
When a train terminates before its last station, it might provoke a false-positive "cancelled station". In this example, the RE 8 19074 terminates in Lauda instead of Würzburg Hbf. Both stops have the `cancelled` key set to `true`, however Lauda still has a `arrival`, a `arrivalDelay` and a `arrivalPlatform`, every `departure`-tag is set to null. I'm guessing that `cancelled` might only be an indicater whether the train still departs from this stop.

**To Reproduce**
Find a Train with cancelled last stop.

**Expected behavior**
Show the correct stops.

**Additional context**
Tested on 2020-02-21 with `1|262777|0|80|21022020` between 15:50 and 16:10.

API-Response:
```json
{"origin":{"type":"stop","id":"8000096","name":"Stuttgart Hbf","location":{"type":"location","id":"8000096","latitude":48.785052,"longitude":9.182589},"products":{"nationalExpress":true,"national":true,"regionalExp":true,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":true,"taxi":false}},"destination":{"type":"stop","id":"8000260","name":"Würzburg Hbf","location":{"type":"location","id":"8000260","latitude":49.802163,"longitude":9.93593},"products":{"nationalExpress":true,"national":true,"regionalExp":false,"regional":true,"suburban":false,"bus":true,"ferry":false,"subway":false,"tram":true,"taxi":false}},"departure":"2020-02-21T15:05:00+01:00","arrival":null,"reachable":true,"line":{"type":"line","id":"re-8","fahrtNr":"19074","name":"RE 8","public":true,"mode":"train","product":"regional","operator":{"type":"operator","id":"go-ahead-baden-wurttemberg-gmbh","name":"Go-Ahead Baden-Württemberg GmbH"},"additionalName":"RE 8"},"direction":"Würzburg Hbf","arrivalPlatform":null,"departurePlatform":"5","stopovers":[{"stop":{"type":"stop","id":"8000096","name":"Stuttgart Hbf","location":{"type":"location","id":"8000096","latitude":48.785052,"longitude":9.182589},"products":{"nationalExpress":true,"national":true,"regionalExp":true,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":true,"taxi":false}},"arrival":null,"arrivalDelay":null,"arrivalPlatform":null,"departure":"2020-02-21T15:05:00+01:00","departureDelay":null,"departurePlatform":"5"},{"stop":{"type":"stop","id":"8000235","name":"Ludwigsburg","location":{"type":"location","id":"8000235","latitude":48.892374,"longitude":9.185115},"products":{"nationalExpress":true,"national":false,"regionalExp":false,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":false}},"arrival":"2020-02-21T15:16:00+01:00","arrivalDelay":null,"arrivalPlatform":"1","departure":"2020-02-21T15:19:00+01:00","departureDelay":null,"departurePlatform":"1"},{"stop":{"type":"stop","id":"8000038","name":"Bietigheim-Bissingen","location":{"type":"location","id":"8000038","latitude":48.948044,"longitude":9.137499},"products":{"nationalExpress":false,"national":false,"regionalExp":false,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":false}},"arrival":"2020-02-21T15:26:00+01:00","arrivalDelay":null,"arrivalPlatform":"10","departure":"2020-02-21T15:29:00+01:00","departureDelay":null,"departurePlatform":"10"},{"stop":{"type":"stop","id":"8000157","name":"Heilbronn Hbf","location":{"type":"location","id":"8000157","latitude":49.143245,"longitude":9.207579},"products":{"nationalExpress":true,"national":false,"regionalExp":false,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":false}},"arrival":"2020-02-21T15:47:00+01:00","arrivalDelay":null,"arrivalPlatform":"3","departure":"2020-02-21T15:48:00+01:00","departureDelay":null,"departurePlatform":"3"},{"stop":{"type":"stop","id":"8004220","name":"Neckarsulm","location":{"type":"location","id":"8004220","latitude":49.188668,"longitude":9.219759},"products":{"nationalExpress":false,"national":false,"regionalExp":false,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":false}},"arrival":"2020-02-21T15:52:00+01:00","arrivalDelay":null,"arrivalPlatform":"1","departure":"2020-02-21T15:52:00+01:00","departureDelay":null,"departurePlatform":"1"},{"stop":{"type":"stop","id":"8000017","name":"Bad Friedrichshall Hbf","location":{"type":"location","id":"8000017","latitude":49.231205,"longitude":9.200091},"products":{"nationalExpress":false,"national":false,"regionalExp":false,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":false}},"arrival":"2020-02-21T15:57:00+01:00","arrivalDelay":0,"arrivalPlatform":"3","departure":"2020-02-21T15:58:00+01:00","departureDelay":0,"departurePlatform":"3"},{"stop":{"type":"stop","id":"8004050","name":"Möckmühl","location":{"type":"location","id":"8004050","latitude":49.321187,"longitude":9.357977},"products":{"nationalExpress":false,"national":false,"regionalExp":false,"regional":true,"suburban":false,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":false}},"arrival":"2020-02-21T16:14:00+01:00","arrivalDelay":0,"arrivalPlatform":"2","departure":"2020-02-21T16:15:00+01:00","departureDelay":0,"departurePlatform":"2"},{"stop":{"type":"stop","id":"8000295","name":"Osterburken","location":{"type":"location","id":"8000295","latitude":49.42992,"longitude":9.422996},"products":{"nationalExpress":false,"national":false,"regionalExp":false,"regional":true,"suburban":true,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":true}},"arrival":"2020-02-21T16:26:00+01:00","arrivalDelay":0,"arrivalPlatform":"4","departure":"2020-02-21T16:27:00+01:00","departureDelay":0,"departurePlatform":"4"},{"stop":{"type":"stop","id":"8000221","name":"Lauda","location":{"type":"location","id":"8000221","latitude":49.56537,"longitude":9.70959},"products":{"nationalExpress":false,"national":false,"regionalExp":false,"regional":true,"suburban":false,"bus":true,"ferry":false,"subway":false,"tram":false,"taxi":true}},"arrival":"2020-02-21T16:49:00+01:00","arrivalDelay":0,"arrivalPlatform":"3","departure":null,"departureDelay":null,"departurePlatform":null,"cancelled":true,"formerDepartureDelay":null,"scheduledDeparture":"2020-02-21T16:50:00+01:00"},{"stop":{"type":"stop","id":"8000260","name":"Würzburg Hbf","location":{"type":"location","id":"8000260","latitude":49.802163,"longitude":9.93593},"products":{"nationalExpress":true,"national":true,"regionalExp":false,"regional":true,"suburban":false,"bus":true,"ferry":false,"subway":false,"tram":true,"taxi":false}},"arrival":null,"arrivalDelay":null,"arrivalPlatform":null,"departure":null,"departureDelay":null,"departurePlatform":null,"cancelled":true,"formerArrivalDelay":null,"scheduledArrival":"2020-02-21T17:20:00+01:00","remarks":[]}],"remarks":[{"text":"Number of bicycles conveyed limited","type":"hint","code":"bicycle-conveyance","summary":"bicycles conveyed"},{"type":"hint","code":"GL","text":"Conveyance of groups is limited"},{"text":"Behindertengerechtes Fahrzeug","type":"hint","code":"barrier-free-vehicle","summary":"barrier-free vehicle"}],"cancelled":true,"arrivalDelay":null,"scheduledArrival":"2020-02-21T17:20:00+01:00","id":"1|262777|0|80|21022020"}
```

### PR DESCRIPTION
**Pull request by HerrLevin**
Fix #21

### CODE REVIEW

File: app/Http/Controllers/HafasController.php [hunk 1]
```diff
@@ -319,6 +319,11 @@ public static function fetchHafasTrip(string $tripID, string $lineName): HafasTr
                     $updatePayload['departure_platform_real'] = $stopover->departurePlatform;
                 }
             }
+            if (isset($stopover->cancelled)) {
```
Comment (MrKrisKrisu) [inline app/Http/Controllers/HafasController.php]: $updatePayload['cancelled'] = $stopover?->cancelled ?? false;

File: database/migrations/2022_03_03_104050_add_cancelled_attribute_to_stopover.php [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+use Illuminate\Support\Facades\Schema;
+
+return new class extends Migration
+{
+    /**
+     * Run the migrations.
+     *
+     * @return void
+     */
+    public function up()
```
Comment (MrKrisKrisu) [inline database/migrations/2022_03_03_104050_add_cancelled_attribute_to_stopover.php]: void

File: database/migrations/2022_03_03_104050_add_cancelled_attribute_to_stopover.php [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+            $table->boolean('cancelled')->default(false)->after('departure_platform_real');
+        });
+    }
+
+    /**
+     * Reverse the migrations.
+     *
+     * @return void
+     */
+    public function down()
```
Comment (MrKrisKrisu) [inline database/migrations/2022_03_03_104050_add_cancelled_attribute_to_stopover.php]: void

File: database/migrations/2022_03_03_104050_add_cancelled_attribute_to_stopover.php [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+return new class extends Migration
+{
+    /**
+     * Run the migrations.
+     *
+     * @return void
+     */
+    public function up()
+    {
+        Schema::table('train_stopovers', function (Blueprint $table) {
```
Comment (MrKrisKrisu) [inline database/migrations/2022_03_03_104050_add_cancelled_attribute_to_stopover.php]: static function

File: database/migrations/2022_03_03_104050_add_cancelled_attribute_to_stopover.php [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+    }
+
+    /**
+     * Reverse the migrations.
+     *
+     * @return void
+     */
+    public function down()
+    {
+        Schema::table('train_stopovers', function (Blueprint $table) {
```
Comment (MrKrisKrisu) [inline database/migrations/2022_03_03_104050_add_cancelled_attribute_to_stopover.php]: static function

**Review by MrKrisKrisu — CHANGES_REQUESTED** [review]
